

/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */


// Operation related types
export type StoreProductPageSeoQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type StoreProductPageSeoQueryQuery = { site: Maybe<{ siteMetadata: Maybe<{ siteUrl: Maybe<string> }> }>, cmsSeo: Maybe<{ seo: Maybe<{ siteMetadata: Maybe<{ title: Maybe<string>, description: Maybe<string>, titleTemplate: Maybe<string> }> }> }> };


// Query Related Code

export const StoreProductPageSEOQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query StoreProductPageSEOQuery {\n  site {\n    siteMetadata {\n      siteUrl\n    }\n  }\n  cmsSeo {\n    seo {\n      siteMetadata {\n        title\n        description\n        titleTemplate\n      }\n    }\n  }\n}\n",
  sha256Hash: "9febc8e70a542d43e43537dc9863d8b8976c28aefda4cba4b8e6180c200915c9",
  operationName: "StoreProductPageSEOQuery",
}

